apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-query
  namespace: observability
spec:
  rules:
  - http:
      paths:
        - pathType: Prefix
          path: "/jaeger"
          backend:
            service:
              name: jaeger-query
              port:
                number: 16686