apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-query
spec:
  rules:
  - http:
      paths:
        - pathType: Prefix
          path: "/jaeger"
          backend:
            service:
              name: jaeger-query
              port:
                number: 16686
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  template:
    spec:
      containers:
        - args:
            - '--sampling.strategies-file=/etc/jaeger/sampling/sampling.json'
            - '--query.base-path=/jaeger'
          image: 'jaegertracing/all-in-one:1.54.0'
          imagePullPolicy: IfNotPresent
          name: jaeger
  selector:
    matchLabels:
      app: jaeger
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/instance: jaeger
      app.kubernetes.io/managed-by: jaeger-operator
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/part-of: jaeger