apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/argo"
            backend:
              service:
                name: argocd-server
                port:
                  name: http